plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mdforhadreza.mfrpublisher'
    compileSdk 35

    signingConfigs {
        mfrInternal {
            storeFile file('../.signing/mfr-internal.jks')
            storePassword 'mfr-publisher-internal'
            keyAlias 'mfrpublisher'
            keyPassword 'mfr-publisher-internal'
        }
    }

    defaultConfig {
        applicationId 'com.mdforhadreza.mfrpublisher'
        minSdk 26
        targetSdk 35
        versionCode 20
        versionName '2.0.0'
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.mfrInternal
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.mfrInternal
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
